export const data = [
  {
    id: '1',
    name: 'Armchair',
    category: 'Chair',
    rating: '4.9',
    price: '50.2',
    description: 'Accessible environment',
    imgSrc: '/images/help-image-1.jpg',
    galleryImages: ['/images/help-image-1.jpg', '/images/help-image-2.jpg', '/images/help-image-3.jpg'],
  },
  {
    id: '2',
    name: 'Bed',
    category: 'Bed',
    rating: '3.0',
    price: '102.10',
    description: 'Cancellation during the pandemic',
    imgSrc: '/images/help-image-4.jpg',
    galleryImages: ['/images/help-image-4.jpg', '/images/help-image-5.jpg', '/images/help-image-6.jpg'],
  },
  {
    id: '3',
    name: 'Bench',
    category: 'Bench',
    rating: '4.9',
    price: '15',
    description: "Airbnb's actions during the pandemic",
    imgSrc: '/images/help-image-7.jpg',
    galleryImages: ['/images/help-image-7.jpg', '/images/help-image-8.jpg', '/images/help-image-9.jpg'],
  },
  {
    id: '4',
    name: 'Bunk bed',
    category: 'Bed',
    rating: '2.3',
    price: '23.75',
    description: 'Report a problem in the area',
    imgSrc: '/images/help-image-10.jpg',
    galleryImages: ['/images/help-image-10.jpg', '/images/help-image-11.jpg', '/images/help-image-12.jpg'],
  },
  {
    id: '5',
    name: 'Armchair2',
    category: 'Chair',
    rating: '4.9',
    price: '50.2',
    description: 'Accessible environment',
    imgSrc: '/images/help-image-1.jpg',
    galleryImages: ['/images/help-image-1.jpg', '/images/help-image-2.jpg', '/images/help-image-3.jpg'],
  },
  {
    id: '6',
    name: 'Bed2',
    category: 'Bed',
    rating: '3.0',
    price: '102.10',
    description: 'Cancellation during the pandemic',
    imgSrc: '/images/help-image-4.jpg',
    galleryImages: ['/images/help-image-4.jpg', '/images/help-image-5.jpg', '/images/help-image-6.jpg'],
  },
  {
    id: '7',
    name: 'Bench2',
    category: 'Bench',
    rating: '4.9',
    price: '15',
    description: "Airbnb's actions during the pandemic",
    imgSrc: '/images/help-image-7.jpg',
    galleryImages: ['/images/help-image-7.jpg', '/images/help-image-8.jpg', '/images/help-image-9.jpg'],
  },
  {
    id: '8',
    name: 'Bunk bed2',
    category: 'Bed',
    rating: '2.3',
    price: '23.75',
    description: 'Report a problem in the area',
    imgSrc: '/images/help-image-10.jpg',
    galleryImages: ['/images/help-image-10.jpg', '/images/help-image-11.jpg', '/images/help-image-12.jpg'],
  },
]
